[package]
name = "chip-great"
version = "0.1.0"
authors = ["Douglas Reichard <djreichard@ra.rockwell.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
device_query="0.2.8"